require File.dirname(__FILE__) + '/../helpers/test_case'
require 'caruby/util/validation'

class CollectionEventParametersTest < Test::Unit::TestCase
  include CaTissue::TestCase

  def setup
    super
    @scg = defaults.specimen_collection_group
    @spc = defaults.specimen
  end
  
  def test_scg_owner_conflict
    assert_raises(ValidationError, "Owner conflict allowed") { @scg.received_event_parameters.specimen = @spc }
  end
  
  def test_specimen_owner_conflict
    @spc.collect(:receiver => @scg.receiver)
    assert_raises(ValidationError, "Owner conflict allowed") { @spc.received_event_parameters.specimen_collection_group = @scg }
  end
  
  def test_update_scg_cep
    assert_nothing_raised("#{@scg} not created") { database.create(@scg) }
    cep = @scg.collection_event_parameters
    assert_not_nil(cep, "Autogenerated #{@scg} CEP not found")
    assert_not_nil(cep.identifier, "Autogenerated #{@scg} CEP identifier not set")
    cep.collection_procedure = 'Lavage'
    logger.debug { "Updating autogenerated #{@scg.qp} CEP #{cep}..." }
    verify_save(cep)
  end
  
  def test_update_specimen_cep
    assert_nothing_raised("#{@scg} not created") { database.create(@spc) }
    cep = @spc.collection_event_parameters
    assert_not_nil(cep, "Autogenerated #{@spc} CEP not found")
    assert_not_nil(cep.identifier, "Autogenerated #{@spc} CEP identifier not set")
    cep.collection_procedure = 'Lavage'
    logger.debug { "Updating autogenerated #{@spc.qp} CEP #{cep}..." }
    verify_save(cep)
  end
end