source :rubygems
gemspec

group :development do
  # The Galena example gem
  gem 'galena', :path => File.dirname(__FILE__)
  # Uncomment the following lines as needed if there are changes to a
  # dependency gem. Change the path option to your workspace location.
  # Commit the changed Gemfile and Gemfile.lock to a local git branch
  # rather than to the master branch. Do not check in the local change.
  gem 'jinx', :path => File.dirname(__FILE__) + '/../../../../jinx/core'
  gem 'jinx-migrate', :path => File.dirname(__FILE__) + '/../../../../jinx/migrate'
  gem 'jinx-json', :path => File.dirname(__FILE__) + '/../../../../jinx/json'
  gem 'caruby-core', :path => File.dirname(__FILE__) + '/../../../core', :require => 'caruby'
  gem 'caruby-tissue', :path => File.dirname(__FILE__) + '/../../../tissue', :require => 'catissue'
end
